name: Windows - LiteManager


on:

workflow_dispatch:


jobs:

build:

name: Start Building...

runs-on: windows-latest

timeout-minutes: 9999



steps:

- name: Downlodaing & Installing Essentials

run:

steo
